In [1]:
import pandas as pd

In [2]:
file = "DATI/2015/" + "1_2015" + '.xlsx'

In [3]:
xl = pd.ExcelFile(file)

In [5]:
df = pd.read_excel (xl, 'Dettaglio Brand & Channel', skiprows = 17 , usecols = "C:E,I:K")

In [6]:
df.head(20)

,TOTAL DIGITAL AUDIENCE,PC,MOBILE,TOTAL DIGITAL AUDIENCE (mm:ss),PC \n(mm:ss),MOBILE (mm:ss)
0,11234,6680,4554,02:58,03:35,02:04
1,177,0,177,00:02,00:00,00:02
2,432928,204658,231007,02:17,02:44,01:52
3,20,20,0,00:32,00:32,00:00
4,10,10,0,00:16,00:16,00:00
5,567,567,0,06:08,06:08,00:00
6,32,32,0,01:47,01:47,00:00
7,110,3,107,00:45,00:30,00:45
8,87,87,0,00:51,00:51,00:00
9,350,268,82,02:09,02:21,01:29
10,142,125,17,01:15,01:24,00:13
11,44459,35404,9055,03:01,02:51,03:37
12,42016,21695,20321,02:24,02:14,02:34
13,2793,2793,0,02:20,02:20,00:00
14,79933,40144,39846,03:09,02:58,03:20
15,31061,18775,12286,03:48,03:19,04:32
16,13712,5669,8043,02:16,02:11,02:20
17,11109,3603,7506,01:59,02:13,01:52
18,10306,5281,5025,03:03,03:07,02:59
19,5280,2821,2459,02:42,03:06,02:15